### ISSUE TITLE
Documentation doesn't fill whole webpage.

### ISSUE THREAD

**Issue by jacobemery** [IBM/Ansible-OpenShift-Provisioning#101]
The [documentation](https://ibm.github.io/Ansible-OpenShift-Provisioning/) web pages don't fill up the entire screen.

It would be amazing if someone could solve this issue!

This problem makes reading things like the tables in [Step 2: Set Variables (group_vars)](https://ibm.github.io/Ansible-OpenShift-Provisioning/set-variables-group-vars/) more difficult as it runs off the page.

The docs were created using [mkdocs](https://www.mkdocs.org/user-guide/writing-your-docs/). Here's how to [install](https://www.mkdocs.org/user-guide/installation/) it.

In this repository, here's the [configuration file](https://github.com/IBM/Ansible-OpenShift-Provisioning/blob/main/mkdocs.yaml) for mkdocs and here's the [folder](https://github.com/IBM/Ansible-OpenShift-Provisioning/tree/main/docs) for all the content on the docs site.

The docs use GitHub pages to deploy. After installing mkdocs, use the following command to create a local deployment for testing purposes use:
```
mkdocs serve
```
and then when it's ready use this command to deploy to GitHub:
```
mkdocs gh-deploy
```
Although, I believe you won't be able to deploy GitHub pages directly, so just open a Pull Request and I will test it and deploy for you.

**Comment by mmondics** [comment]
This is just how the `readthedocs` mkdocs theme is configured. The easiest solution would be to use a different theme and update it in your `mkdocs.yaml`. There's a list here: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes. Here's an example of `material`.

<img width="1789" alt="Screenshot 2023-12-29 at 10 03 49 AM" src="https://github.com/IBM/Ansible-OpenShift-Provisioning/assets/46940343/e2138fb7-e22f-4a15-bd1e-2a7614b28bd0">

If you want to keep the `readthedocs` theme, you'll have to do some tinkering with custom styling. It comes down to adding a custom css file to your `docs` directory and referencing it in your `mkdocs.yaml`. Here's an example.

<img width="1790" alt="Screenshot 2023-12-29 at 10 14 53 AM" src="https://github.com/IBM/Ansible-OpenShift-Provisioning/assets/46940343/bf90f11f-9cb2-4ddb-bdcb-700b6f3b5841">

Let me know if either of these look good to you and I can open a pull request.

**Comment by jacobemery** [comment]
PR #288 fixed this, thanks @mmondics!
