### ISSUE TITLE
NAT for prod environment

### ISSUE THREAD

**Issue by irmsan** [IBM/Ansible-OpenShift-Provisioning#117]
Dear developers,

can you pls extend the NAT possibility toward the HA (=3 KVMs) setup as well?
Together with this pls consider, what happens, if the HOP is from KVM to Bastion, what happens when the Bastion is down?

Probably in a HA setup a 2nd bastion(haproxy etc) is required ...

**Comment by jacobemery** [comment]
Talked with @irmsan and he has tested NAT across 3 LPARs and has determined it to not be possible, or at least prohibitively difficult. 

Closing this issue because if a production deployment is required (spread across 3 LPARs), it's best to stick with macvtap anyway.
