### ISSUE TITLE
Can not install all released OCP versions

### ISSUE THREAD

**Issue by smolin-de** [IBM/Ansible-OpenShift-Provisioning#129]
We have problem with the OpenShift version definition in the Ansible-Openshift-provisioning tool.
The variable “env.openshift.version” is also used to specify the RHCOS version.
But, the RHCOS image versions are different.
You can specify OCP version 4.12.6, but there is no RHCOS 4.12.6. The latest RHCOS version is 4.12.3.
So, you can not install all released OCP versions !

**Comment by smolin-de** [comment]
This above issues is solved with this PR:
https://github.com/IBM/Ansible-OpenShift-Provisioning/pull/126

**Comment by irmsan** [comment]
if some can "query" the openshift mirror page, then this could be automated.
let's say the target is 4.11.37, for that the demand is to find the "latest" 4.11 RHCOS (before or equal to 37"

**Comment by smolin-de** [comment]
> if some can "query" the openshift mirror page, then this could be automated. let's say the target is 4.11.37, for that the demand is to find the "latest" 4.11 RHCOS (before or equal to 37"

Yes a query could be implemented. But, which repo you want to query ? 
I need this tool to test new OCP releases and new RHCOS releases (Nightly builds, EC build, RC builds ...). 
My patch gives the user the ability to define any desired combination of OCP and RHCOS.

**Comment by irmsan** [comment]
query the repo what a user adds in the all.yaml file.
If he adds for example 4.11.37, querry the mirror. which is the closest (latest) RHCOS to that, and download it
