### ISSUE TITLE
env.bridge_name - Documentation / naming unclear.

### ISSUE THREAD

**Issue by ryoung1us** [IBM/Ansible-OpenShift-Provisioning#163]
env.bridge_name  seems to be documented as the name of a bridge the ansible will create.    

1) This is not a bridge that gets created, it is a KVM network definition (as in virsh net-define).  Clarlity on this point in the documentation as well as the variable naming would be helpful.
2) The function appears to be dual purpose.   a) Which network interface to connect to  b) what to call the KVM network definition.   This is not discussed in the documentation, and you may want to have separate variable for each item.
3) Documentation  should recommend using something like a bond interface and not and encX interface

**Comment by AmadeusPodvratnik** [comment]
Variable name was renamed and documentation enhanced. Due to the amount of variables new variables should be limited.
