### ISSUE TITLE
Playbook 5 says dig validation of DNS fails, but dig lookup commands are succesful

### ISSUE THREAD

**Issue by ryoung1us** [IBM/Ansible-OpenShift-Provisioning#166]
Ansible Output:

TASK [dns : Template out bastion's resolv.conf file, replacing initial resolv.conf] ***************************************************************************************
skipping: [bastion.ocp1.ibm.com]

TASK [dns : Restart network to update changes made to /etc/resolv.conf] ***************************************************************************************************
skipping: [bastion.ocp1.ibm.com]

TASK [check_dns : Check internal cluster DNS resolution for the bastion] **************************************************************************************************
changed: [bastion.ocp1.ibm.com]

TASK [check_dns : Check internal cluster DNS resolution for external API and apps services] *******************************************************************************
failed: [bastion.ocp1.ibm.com] (item=api.ocp1.ibm.com) => {"ansible_loop_var": "item", "changed": true, "cmd": "dig +short api.ocp1.ibm.com | tail -n1", "delta": "0:00:00.007357", "end": "2023-06-03 20:20:19.514264", "failed_when_result": true, "item": "api.ocp1.ibm.com", "msg": "", "rc": 0, "start": "2023-06-03 20:20:19.506907", "stderr": "", "stderr_lines": [], "stdout": "9.76.61.80", "stdout_lines": ["9.76.61.80"]}
failed: [bastion.ocp1.ibm.com] (item=apps.ocp1.ibm.com) => {"ansible_loop_var": "item", "changed": true, "cmd": "dig +short apps.ocp1.ibm.com | tail -n1", "delta": "0:00:00.006574", "end": "2023-06-03 20:20:19.777103", "failed_when_result": true, "item": "apps.ocp1.ibm.com", "msg": "", "rc": 0, "start": "2023-06-03 20:20:19.770529", "stderr": "", "stderr_lines": [], "stdout": "9.76.61.80", "stdout_lines": ["9.76.61.80"]}
failed: [bastion.ocp1.ibm.com] (item=test.apps.ocp1.ibm.com) => {"ansible_loop_var": "item", "changed": true, "cmd": "dig +short test.apps.ocp1.ibm.com | tail -n1", "delta": "0:00:00.007048", "end": "2023-06-03 20:20:20.039085", "failed_when_result": true, "item": "test.apps.ocp1.ibm.com", "msg": "", "rc": 0, "start": "2023-06-03 20:20:20.032037", "stderr": "", "stderr_lines": [], "stdout": "9.76.61.80", "stdout_lines": ["9.76.61.80"]}

PLAY RECAP ****************************************************************************************************************************************************************
127.0.0.1                  : ok=8    changed=4    unreachable=0    failed=0    skipped=18   rescued=0    ignored=0   
bastion.ocp1.ibm.com       : ok=20   changed=15   unreachable=0    failed=1    skipped=16   rescued=0    ignored=0   

Actual dig command from bastion

[root@bastion ~]# dig +short api.ocp1.ibm.com
9.76.61.80
[root@bastion ~]# dig +short apps.ocp1.ibm.com 
9.76.61.80
[root@bastion ~]# dig +short test.apps.ocp1.ibm.com
9.76.61.80

**Comment by AmadeusPodvratnik** [comment]
@ryoung1us It looks like that your case is addressing an external dns server, correct?
