### ISSUE TITLE
Ipv6 ULA address is not assigned for OCP nodes when OCP is installed on KVM

### ISSUE THREAD

**Issue by amrutp-redhat** [IBM/Ansible-OpenShift-Provisioning#199]
OCP Bring up with IPV6 on KVM for Dual Stack support  

Once OCP is installed , ocp nodes doesn't get IPV6 ULA address. 

`NAME       STATUS   ROLES                  AGE   VERSION
master-0   Ready    control-plane,master   33m   v1.27.4+2c83a9f
master-1   Ready    control-plane,master   32m   v1.27.4+2c83a9f
master-2   Ready    control-plane,master   31m   v1.27.4+2c83a9f
worker-0   Ready    worker                 17m   v1.27.4+2c83a9f
worker-1   Ready    worker                 16m   v1.27.4+2c83a9f
[root@bastion network-scripts]# oc get clusterversion
NAME      VERSION       AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.14.0-rc.0   True        False         5m46s   Cluster version is 4.14.0-rc.0
[root@bastion network-scripts]# oc get co
NAME                                       VERSION       AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.14.0-rc.0   True        False         False      6m22s   
baremetal                                  4.14.0-rc.0   True        False         False      28m     
cloud-controller-manager                   4.14.0-rc.0   True        False         False      33m     
cloud-credential                           4.14.0-rc.0   True        False         False      32m     
cluster-autoscaler                         4.14.0-rc.0   True        False         False      28m     
config-operator                            4.14.0-rc.0   True        False         False      29m     
console                                    4.14.0-rc.0   True        False         False      12m     
control-plane-machine-set                  4.14.0-rc.0   True        False         False      28m     
csi-snapshot-controller                    4.14.0-rc.0   True        False         False      29m     
dns                                        4.14.0-rc.0   True        False         False      27m     
etcd                                       4.14.0-rc.0   True        False         False      27m     
image-registry                             4.14.0-rc.0   True        False         False      17m     
ingress                                    4.14.0-rc.0   True        False         False      15m     
insights                                   4.14.0-rc.0   True        False         False      22m     
kube-apiserver                             4.14.0-rc.0   True        False         False      25m     
kube-controller-manager                    4.14.0-rc.0   True        False         False      25m     
kube-scheduler                             4.14.0-rc.0   True        False         False      25m     
kube-storage-version-migrator              4.14.0-rc.0   True        False         False      29m     
machine-api                                4.14.0-rc.0   True        False         False      28m     
machine-approver                           4.14.0-rc.0   True        False         False      28m     
machine-config                             4.14.0-rc.0   True        False         False      28m     
marketplace                                4.14.0-rc.0   True        False         False      28m     
monitoring                                 4.14.0-rc.0   True        False         False      9m15s   
network                                    4.14.0-rc.0   True        False         False      28m     
node-tuning                                4.14.0-rc.0   True        False         False      16m     
openshift-apiserver                        4.14.0-rc.0   True        False         False      22m     
openshift-controller-manager               4.14.0-rc.0   True        False         False      22m     
openshift-samples                          4.14.0-rc.0   True        False         False      21m     
operator-lifecycle-manager                 4.14.0-rc.0   True        False         False      28m     
operator-lifecycle-manager-catalog         4.14.0-rc.0   True        False         False      28m     
operator-lifecycle-manager-packageserver   4.14.0-rc.0   True        False         False      22m     
service-ca                                 4.14.0-rc.0   True        False         False      29m     
storage                                    4.14.0-rc.0   True        False         False      29m  `

Bastion got ipv6 ula address but ocp master and worker nodes has got private ip4 address only. ipv6 ula address is not assigned.

`bastion
[root@bastion network-scripts]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enc1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:b6:a0:5e brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.2/24 brd 192.168.122.255 scope global noprefixroute enc1
       valid_lft forever preferred_lft forever
    inet6 fd03::22/128 scope global dynamic noprefixroute 
       valid_lft 3325sec preferred_lft 3325sec
    inet6 fe80::5054:ff:feb6:a05e/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

Last login: Wed Sep 13 17:28:30 2023 from 192.168.122.2
[core@master-0 ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enc1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master ovs-system state UP group default qlen 1000
    link/ether 52:54:00:32:1c:8c brd ff:ff:ff:ff:ff:ff
4: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 2e:fa:5f:a8:43:1b brd ff:ff:ff:ff:ff:ff
5: br-ex: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 52:54:00:32:1c:8c brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.4/24 brd 192.168.122.255 scope global noprefixroute br-ex
       valid_lft forever preferred_lft forever
    inet 169.254.169.2/29 brd 169.254.169.7 scope global br-ex
       valid_lft forever preferred_lft forever
6: br-int: <BROADCAST,MULTICAST> mtu 1400 qdisc noop state DOWN group default qlen 1000
    link/ether 56:7d:56:87:69:14 brd ff:ff:ff:ff:ff:ff
7: ovn-k8s-mp0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 36:aa:7f:46:f7:eb brd ff:ff:ff:ff:ff:ff
    inet 10.130.0.2/23 brd 10.130.1.255 scope global ovn-k8s-mp0
       valid_lft forever preferred_lft forever
    inet6 fe80::34aa:7fff:fe46:f7eb/64 scope link 
       valid_lft forever preferred_lft forever

worker-0
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enc1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master ovs-system state UP group default qlen 1000
    link/ether 52:54:00:7c:8d:dd brd ff:ff:ff:ff:ff:ff
4: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 7e:bb:6f:87:16:be brd ff:ff:ff:ff:ff:ff
5: br-ex: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 52:54:00:7c:8d:dd brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.7/24 brd 192.168.122.255 scope global noprefixroute br-ex
       valid_lft forever preferred_lft forever
    inet 169.254.169.2/29 brd 169.254.169.7 scope global br-ex
       valid_lft forever preferred_lft forever
6: br-int: <BROADCAST,MULTICAST> mtu 1400 qdisc noop state DOWN group default qlen 1000
    link/ether 9a:4a:e4:35:1f:48 brd ff:ff:ff:ff:ff:ff
7: ovn-k8s-mp0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 92:f0:51:7f:9d:5e brd ff:ff:ff:ff:ff:ff
    inet 10.131.0.2/23 brd 10.131.1.255 scope global ovn-k8s-mp0
       valid_lft forever preferred_lft forever
    inet6 fe80::90f0:51ff:fe7f:9d5e/64 scope link 
       valid_lft forever preferred_lft forever `

**Comment by AmadeusPodvratnik** [comment]
Will be fixed with #209 ...

**Comment by AmadeusPodvratnik** [comment]
Fix done. Defect can be closed. @amrutp-redhat

**Comment by AmadeusPodvratnik** [comment]
close ...
