### ISSUE TITLE
setup bastion fails for 3 node cluster definition

### ISSUE THREAD

**Issue by AmadeusPodvratnik** [IBM/Ansible-OpenShift-Provisioning#252]
Playbook 5 fails for a 3 node cluster:

TASK [dns : Add compute nodes to DNS reverse lookup file on bastion] ************************************************************************************************************
fatal: [bastion]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'None' has no attribute 'split'. 'None' has no attribute 'split'\n\nThe error appears to be in '/Users/pod/Documents/Business/OCP/DevItems/release/Ansible-OpenShift-Provisioning/roles/dns/tasks/main.yaml': line 97, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add compute nodes to DNS reverse lookup file on bastion\n  ^ here\n"}

# Section 9 - Compute Nodes
      compute:
        disk_size: 120
        ram: 16384
        vcpu: 4
        vcpu_model_option: "--cpu host"
        vm_name:
          - #X
          - #X
        ip:
          - #X
          - #X
        ipv6:
          - #X
          - #X
        mac:
          - #X
          - #X
        hostname:
          - #X
          - #X

**Comment by smolin-de** [comment]
Ok, good catch.
I am using an external DNS in my setup.
