### ISSUE TITLE
Patch  #249 does not work. Should be reverted.

### ISSUE THREAD

**Issue by smolin-de** [IBM/Ansible-OpenShift-Provisioning#254]
The Patch  #249 tries to reconfigure and restart HAProxy on a KVM host. HAProxy is installed on a Bastion host, if enabled.

**Comment by smolin-de** [comment]
fyi.
@k-shiva-sai

**Comment by k-shiva-sai** [comment]
Ohh I missed this I will look into it @smolin-de 
Thanks for letting me know

**Comment by k-shiva-sai** [comment]
#255
