### ISSUE TITLE
Openshift installer tarball for rhel 9 extracts to `openshift-install-fips`

### ISSUE THREAD

**Issue by mohammedzee1000** [IBM/Ansible-OpenShift-Provisioning#305]
From OCP 4.16 onwards a new separate installer tarball is added for rhel 9 (openshift-install-rhel9-s390x.tar.gz).
The normal binary is for rhel 8.

Downloading this and extracting it results in installer binary called `openshift-install-fips` instead of `openshift-install`.
This will cause AOP install to fail as it wont find `openshift-install` binary.

```bash
❯ wget https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/4.16.5/openshift-install-rhel9-s390x.tar.gz
❯ tar -xzf openshift-install-rhel9-s390x.tar.gz
❯ ls
 openshift-install-fips   openshift-install-rhel9-s390x.tar.gz
```

**Comment by mohammedzee1000** [comment]
A possible work around for this is to mirror the installer and oc client tarballs
You download, extract, rename the installer binary, host it in a location on a file server and provide that URL to `clients_download_url`

A possible fix would be to detect the binary name after extraction and rename it
in shell this can be done as below
```bash
FN=`ls openshift-install*`
if [[ $FN != "openshift-install" ]]; then
    mv $FN openshift-install
fi
```

Of course we would do similar thing in ansible.

**Comment by mohammedzee1000** [comment]
I think this affects any rhel 9 bastion based install

**Comment by AmadeusPodvratnik** [comment]
@mohammedzee1000 With this PR you are able to use fips to install OCP using ABI.
