### ISSUE TITLE
Error to place proxy info inti install_config.yaml

### ISSUE THREAD

**Issue by irmsan** [IBM/Ansible-OpenShift-Provisioning#306]
using PROXY still in error
the condition is:
    use_proxy: "{{ 'True' if (proxy_env.http_proxy is defined or proxy_env.https_proxy is defined or [proxy_env.no](http://proxy_env.no/)_proxy is defined) else 'False' }}"

proxy_env.http_proxy variable not exists , it should be env.proxy.http I guess and same for https

Additionally In the template:
my advise, put the localhost into back to the all.yaml [env.proxy.no](http://env.proxy.no/) 
and in same place  (in the template) inserting the INFRA nodes to the noProxy should be CONDITIONAL

**Comment by AmadeusPodvratnik** [comment]
@irmsan There will be this PR https://github.com/IBM/Ansible-OpenShift-Provisioning/pull/327 which use a flag and flatten several vars and make defaults for a bunch of parms.
