### ISSUE TITLE
SNO install is broken

### ISSUE THREAD

**Issue by smolin-de** [IBM/Ansible-OpenShift-Provisioning#315]
We have two SNO install methods. With bootstrap node and without an bootstrap node.
A resent patch added a sno_haproxy role for an installation without bootstrap node.

    - { role: haproxy, when: env.bastion.options.loadbalancer.on_bastion }
    - { role: sno_haproxy, when: env.bastion.options.loadbalancer.on_bastion and control_node_count | int == 1 }

The issue is, that the sno_haproxy role is always used on a single node installation.
You can only use SNO installs **without** bootstrap.

The second issue is, that the SNO ignition file is always created without the option: single-node-ignition-config
The ignition file **with** bootstrap is used for an SNO installation.

The SNO haproxy setup does not match with the SNO ignition setup!

**Comment by isumitsolanki** [comment]
Hi @smolin-de , This issue has been resolved in https://github.com/IBM/Ansible-OpenShift-Provisioning/pull/324 PR

**Comment by isumitsolanki** [comment]
This issue has been resolved. hence closing

**Comment by isumitsolanki** [comment]
Hi @smolin-de , this issue has been resolved. please verify from your end and let me know if issue is still. there
